-- MySQL Script generated by MySQL Workbench
-- Mon Dec 13 16:49:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e-commerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `e-commerce` ;

-- -----------------------------------------------------
-- Table `e-commerce`.`cats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`cats` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
 `created_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `cat_id` INT UNSIGNED NOT NULL,
    `price` DECIMAL(9,2) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `piecesNo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cats_cats_idx` (`cat_id` ASC) ,
  CONSTRAINT `fk_cats_cats`
    FOREIGN KEY (`cat_id`)
    REFERENCES `e-commerce`.`cats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `status_of_order` ENUM('pendding', 'approve', 'canceled') NOT NULL DEFAULT 'pendding',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`orders_details_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`orders_details_product` (
  `orders_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `qty` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `product_id`),
  INDEX `fk_orders_has_product_product1_idx` (`product_id` ASC) ,
  INDEX `fk_orders_has_product_orders1_idx` (`orders_id` ASC) ,
  CONSTRAINT `fk_orders_has_product_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `e-commerce`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `e-commerce`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-commerce`.`admins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_super` ENUM('yes', 'no') NOT NULL DEFAULT 'no',
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
